export const ethnicityOptions = [
  { id: "eng", name: "English", label: "english", group: "white" },
  { id: "welsh", name: "Welsh", label: "welsh", group: "white" },
  { id: "scottish", name: "Scottish", label: "scottish", group: "white" },
  {
    id: "northernIrish",
    name: "Northern Irish",
    label: "northernIrish",
    group: "white",
  },
  { id: "irish", name: "Irish", label: "irish", group: "white" },
  {
    id: "gypsy",
    name: "Gypsy or Irish Traveller",
    label: "gypsyOrIrishTraveller",
    group: "white",
  },
  {
    id: "otherWhites",
    name: "Any Other White Background",
    label: "otherWhites",
    group: "white",
  },
  {
    id: "whiteAndBlackCaribbean",
    name: "White and Black Caribbean",
    label: "whiteAndBlackCaribbean",
    group: "mixed",
  },
  {
    id: "whiteAndBlackAfrican",
    name: "White and Black African",
    label: "whiteAndBlackAfrican",
    group: "mixed",
  },
  {
    id: "otherMixed",
    name: "Any other Mixed or Multiple background",
    label: "otherMixed",
    group: "mixed",
  },
  { id: "indian", name: "Indian", label: "indian", group: "asian" },
  { id: "pakistani", name: "Pakistani", label: "pakistani", group: "asian" },
  {
    id: "bangladeshi",
    name: "Bangladeshi",
    label: "bangladeshi",
    group: "asian",
  },
  { id: "chinese", name: "Chinese", label: "chinese", group: "asian" },
  {
    id: "otherAsian",
    name: "Any other Asian background",
    label: "otherAsian",
    group: "asian",
  },
  { id: "african", name: "African", label: "african", group: "black" },
  {
    id: "africanAmerican",
    name: " African American",
    label: "africanAmerican",
    group: "black",
  },
  { id: "carribean", name: "Carribean", label: "carribean", group: "black" },
  {
    id: "otherBlack",
    name: "Any other Asian background",
    label: "otherBlack",
    group: "black",
  },
  { id: "arab", name: "Arab", label: "arab", group: "others" },
  { id: "hispanic", name: "Hispanic", label: "hispanic", group: "others" },
  { id: "latino", name: "Latino", label: "latino", group: "others" },
  {
    id: "nativeAmerican",
    name: "Native American",
    label: "nativeAmerican",
    group: "others",
  },
  {
    id: "pacificIslander",
    name: "Pacific Islander",
    label: "pacificIslander",
    group: "others",
  },
  {
    id: "otherEthnic",
    name: "Any Other Ethnic Group",
    label: "otherEthnic",
    group: "others",
  },
];

export const genderOptions = [
  { id: "female", label: "female", name: "Female" },
  { id: "male", label: "male", name: "Male" },
  { id: "non-binary", label: "non-binary", name: "Non-binary" },
  { id: "other", label: "other", name: "Other" },
  { id: "noAnswer", label: "noAnswer", name: "Prefer not to answer" },
];

export const countryOptions = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const departmentOptions = [
  "Human Resources",
  "Finance",
  "Information Technology",
  "Sales",
  "Research and Development",
  "Marketing",
  "Production",
  "Financial Accounting",
  "Customer Service",
  "Operations Management",
  "Quality Management",
  "Business Administration",
  "Design",
  "Security",
  "Distribution",
  "Management",
  "Operations and Production",
  "Accounts",
];

export const yesOrNoOptions = [
  { id: "yes", name: "Yes", label: "yes" },
  { id: "no", name: "No", label: "no" },
];
